### ISSUE TITLE
ProblemFile and source term

### ISSUE THREAD

**Issue by loganoz** [loganoz/horses3d#138]
Can someone take a look to what happens when we use the standard ProblemFile without adding any source term? 
S is defined in the problem file as an input-output variable.
However, it does not seem to be defined anywhere in the code. What's the initial value of S? I think it is compiler dependent and a source of possible errors.

**Comment by oscarmarino** [comment]
S_NS is allocated and set to 0 at the begging of the simulation in the storage construction. Also in SpatialDiscretization is set to 0 before calling the problem file each time Qdot is computed. In the problem file is inout so that if nothing is done it remains 0 (that is the standard ProblemFile or one that only changes other thing, as IC or BC).

**Comment by stecolumbus** [comment]
I think that the source term is also used in multi grid. I agree with Oscar regarding what he said.

**Comment by loganoz** [comment]
Good. It only gives problems in the truncation error estimation then. Thanks!
